doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 90
autodetect: true
ignore-paths:
  - docs
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 3
